version: "3"

services:
  postgres:
    image: postgres
    env_file:
      - .env.example
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env.example
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - server
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env.example
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - server
      - db

networks:
  server:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres:
